"""
MIA — Topología del modelo (curada a mano desde el código, 2026-08-19).
=======================================================================
Lo que un escáner NO puede deducir: qué fuente oficial alimenta a cada script,
qué produce cada uno, y cuáles son insumos/alertas en vez de valor publicado.
La parte declarativa (18 variables, anclas, pesos, núcleo) NO se repite acá:
sale de 00_Comun/variables.yaml. Este archivo solo describe las cañerías.

Lo lee scripts/generar_mapa_modelo.py.
"""

# ── Fuentes oficiales externas ───────────────────────────────────────────────
FUENTES = [
    {"id": "f_infoleg", "corto": "InfoLEG", "label": "InfoLEG — Normativa Nacional", "host": "datos.jus.gob.ar",
     "nota": "Dataset ZIP de la 1ª Sección del BO desde 1997. Marca oficial clase_norma='DNU' (ADR 0006).", "ip_ar": True},
    {"id": "f_dgsiaf", "corto": "DGSIAF", "label": "DGSIAF — crédito anual y mensual", "host": "dgsiaf-repo.mecon.gob.ar",
     "nota": "Ejecución presupuestaria. Cuatro variables salen de acá (ATN, pauta, costo del Congreso, medios estatales).", "ip_ar": True},
    {"id": "f_opc", "corto": "OPC", "label": "OPC — modificaciones presupuestarias", "host": "opc.gob.ar",
     "nota": "Única fuente que ata cada reasignación a su instrumento (DA/DNU). Publica por instrumento desde 2024.", "ip_ar": False},
    {"id": "f_aaip", "corto": "AAIP", "label": "AAIP — microdato sip.csv", "host": "descarga.aaip.gob.ar",
     "nota": "Una fila por pedido de acceso a la información (Ley 27.275).", "ip_ar": True},
    {"id": "f_hcdn_proy", "corto": "HCDN · proyectos", "label": "HCDN — buscador de proyectos", "host": "hcdn.gob.ar",
     "nota": "Frágil y lento; no envía el certificado TLS intermedio (se resuelve con truststore).", "ip_ar": False},
    {"id": "f_hcdn_ses", "corto": "HCDN · sesiones", "label": "HCDN — sesiones", "host": "hcdn.gob.ar",
     "nota": "HTML server-side; una sola página trae todos los períodos.", "ip_ar": False},
    {"id": "f_senado", "corto": "Senado · JGM", "label": "Senado — Informes JGM", "host": "senado.gob.ar",
     "nota": "Tabla estable pero con lag; a veces omite informes que fueron a Diputados.", "ip_ar": False},
    {"id": "f_csjn", "corto": "CSJN · anuarios", "label": "CSJN — Anuarios estadísticos (PDF)", "host": "csjn.gov.ar",
     "nota": "Cadencia ANUAL: entre anuarios la variable queda constante por diseño (ADR: no es un bug).", "ip_ar": False},
    {"id": "f_magistrados", "corto": "datos.jus · magistrados", "label": "datos.jus — Magistrados (CKAN)", "host": "datos.jus.gob.ar",
     "nota": "Snapshot oficial de cargos; se actualiza ~cada 2 años. De ahí la necesidad del padrón vivo.", "ip_ar": True},
    {"id": "f_bora", "corto": "BORA", "label": "Boletín Oficial — 1ª Sección", "host": "boletinoficial.gob.ar",
     "nota": "Lectura por fecha (/seccion/primera/AAAAMMDD). Accesible desde el exterior: por eso los radares corren en la nube.", "ip_ar": False},
    {"id": "f_casarosada", "corto": "Casa Rosada", "label": "Casa Rosada — conferencias y discursos", "host": "casarosada.gob.ar",
     "nota": "Joomla, HTML server-side, paginado ?start=N.", "ip_ar": False},
    {"id": "f_fopea", "corto": "FOPEA", "label": "FOPEA — Monitoreo (WP REST)", "host": "monitoreo.fopea.org",
     "nota": "La categoría del caso vive en el HTML de la ficha como /tag/<slug>/, no en la REST.", "ip_ar": False},
    {"id": "f_bcra_bal", "corto": "BCRA · balance", "label": "BCRA — balance histórico (balbcrhis.xls)", "host": "bcra.gob.ar",
     "nota": "Columnas POR POSICIÓN (15 adelantos, 20 letras, 24 activo, 37 base monetaria).", "ip_ar": True},
    {"id": "f_series", "corto": "Series de Tiempo", "label": "Series de Tiempo — recaudación", "host": "apis.datos.gob.ar",
     "nota": "Serie 172.3_TL_RECAION_M_0_0_17. Excepción: responde desde fuera de Argentina.", "ip_ar": False},
    {"id": "f_pia_oa", "corto": "PIA + OA", "label": "PIA (MPF) + Oficina Anticorrupción", "host": "mpf.gob.ar · argentina.gob.ar",
     "nota": "Informes anuales en PDF. Exploratorio: no alimenta el índice.", "ip_ar": False, "fuera": True},
    {"id": "f_panhis", "corto": "BCRA · panhis", "label": "BCRA — panorama monetario (panhis.xls)", "host": "bcra.gob.ar",
     "nota": "Solo diagnóstico de estructura; no produce serie.", "ip_ar": True, "fuera": True},
]

# ── Scripts: qué leen y qué producen ────────────────────────────────────────
# eje: para el agrupamiento espacial. produce: ids de nodos de dato.
SCRIPTS = [
    {"id": "sc_infoleg", "label": "infoleg_source.py", "archivo": "00_Comun/infoleg_source.py", "eje": "Infra",
     "lee": ["f_infoleg"], "produce": ["d_infoleg_df"], "rol": "librería compartida",
     "nota": "Única copia (2026-08-19). Centraliza descarga robusta, parseo resiliente y fecha coalescida boletín→sanción."},
    {"id": "sc_01", "label": "scraper_01_dnu_leyes.py", "archivo": "01_Poder_Ejecutivo/scraper_01_dnu_leyes.py", "eje": "Ejecutivo",
     "lee": ["d_infoleg_df"], "produce": ["dnu_leyes_mensual"],
     "nota": "DNU = tipo_norma 'Decreto' + clase_norma 'DNU'. La detección por texto quedó como validación cruzada (daba ~40 falsos positivos por citas en los considerandos)."},
    {"id": "sc_04", "label": "scraper_04_discrecionalidad.py", "archivo": "01_Poder_Ejecutivo/scraper_04_discrecionalidad.py", "eje": "Ejecutivo",
     "lee": ["f_opc", "d_infoleg_df", "t_presupuesto"], "produce": ["discrecionalidad_mensual"],
     "nota": "La magnitud en pesos de DGSIAF se descartó (ceros de prórroga, reorganización ministerial, valores negativos). Quedan el flag de régimen y el conteo por instrumento."},
    {"id": "sc_11", "label": "scraper_11_transparencia_v2.py", "archivo": "01_Poder_Ejecutivo/scraper_11_transparencia_v2.py", "eje": "Ejecutivo",
     "lee": ["f_aaip"], "produce": ["transparencia_v2_mensual"],
     "nota": "Fechado por mes de RESOLUCIÓN (fecha_ultimo_pase de los terminales), no de inicio: da la tasa del mes sin esperar a que madure el cohorte."},
    {"id": "sc_16", "label": "scraper_16_atn.py", "archivo": "01_Poder_Ejecutivo/scraper_16_atn.py", "eje": "Ejecutivo",
     "lee": ["f_dgsiaf"], "produce": ["atn_mensual", "d_atn_obs"],
     "nota": "El índice usa el share MENSUAL; el anual queda de referencia y de fallback para el núcleo viejo. Caché solo de años cerrados."},
    {"id": "sc_02", "label": "scraper_02_calidad_normativa.py", "archivo": "02_Poder_Legislativo/scraper_02_calidad_normativa.py", "eje": "Legislativo",
     "lee": ["f_hcdn_proy", "d_infoleg_df"], "produce": ["calidad_normativa_mensual"],
     "nota": "Leyes sancionadas de InfoLEG + simbólicas del buscador HCDN. El mes en curso nunca se cachea (su conteo es parcial)."},
    {"id": "sc_03", "label": "scraper_03_eficacia_control.py", "archivo": "02_Poder_Legislativo/scraper_03_eficacia_control.py", "eje": "Legislativo",
     "lee": ["f_senado", "t_informes"], "produce": ["eficacia_control_mensual"],
     "nota": "Cumplimiento del art. 101 CN: concurrencias del JGM sobre el mínimo de 12 al año. Dedup por número de informe (partes, tomos y anexos)."},
    {"id": "sc_12", "label": "scraper_12_costo_legislativo.py", "archivo": "02_Poder_Legislativo/scraper_12_costo_legislativo.py", "eje": "Legislativo",
     "lee": ["f_dgsiaf"], "produce": ["costo_legislativo_mensual"],
     "nota": "Jurisdicción Poder Legislativo excluyendo AGN, Defensoría del Pueblo y CNPT (no son costo del Congreso)."},
    {"id": "sc_14", "label": "scraper_14_sesiones.py", "archivo": "02_Poder_Legislativo/scraper_14_sesiones.py", "eje": "Legislativo",
     "lee": ["f_hcdn_ses"], "produce": ["sesiones_mensual"],
     "nota": "Citadas vs realizadas (descarta 'no efectuada', 'fracasada', 'en minoría' y la Asamblea Legislativa)."},
    {"id": "sc_05", "label": "scraper_05_cobertura_judicial.py", "archivo": "03_Poder_Judicial/scraper_05_cobertura_judicial.py", "eje": "Judicial",
     "lee": ["f_magistrados", "d_altas", "d_padron_tasas"], "produce": ["cobertura_judicial_mensual"],
     "nota": "Universo consistente: SOLO jueces. Stock del snapshot + estimado del padrón para el mes corriente + flujo con max(fecha dataset, fecha radar)."},
    {"id": "sc_06", "label": "scraper_06_resolucion_csjn.py", "archivo": "03_Poder_Judicial/scraper_06_resolucion_csjn.py", "eje": "Judicial",
     "lee": ["f_csjn", "t_csjn"], "produce": ["resolucion_csjn_mensual"],
     "nota": "Auto-parse del PDF validado contra cifras verificadas a mano; la composición de la Corte (vacantes) es tabla mantenida."},
    {"id": "sc_padron", "label": "padron_judicial.py", "archivo": "03_Poder_Judicial/padron_judicial.py", "eje": "Judicial",
     "lee": ["f_magistrados", "d_altas", "d_bajas"], "produce": ["d_padron_tasas", "d_padron_revision"],
     "nota": "Padrón vivo: un cargo por fila. Aplica solo eventos ALTA/confirmados POSTERIORES al snapshot (si no, se contaría dos veces). Matching por tokens + número de juzgado releyendo el decreto."},
    {"id": "sc_10", "label": "scraper_10_integridad.py", "archivo": "03_Poder_Judicial/scraper_10_integridad.py", "eje": "Judicial",
     "lee": ["f_pia_oa"], "produce": ["d_integridad"], "fuera": True,
     "nota": "«Control de la corrupción» se descartó por falta de dato duro y su 8% se redistribuyó en Corte + Cobertura. Queda como exploración."},
    {"id": "sc_07", "label": "scraper_07_escrutinio.py", "archivo": "04_Prensa_Institucional/scraper_07_escrutinio.py", "eje": "Prensa",
     "lee": ["f_casarosada"], "produce": ["escrutinio_mensual"],
     "nota": "Conferencias de prensa (se expone a preguntas) sobre conferencias + cadenas nacionales (monólogo obligatorio)."},
    {"id": "sc_08", "label": "scraper_08_pauta.py", "archivo": "04_Prensa_Institucional/scraper_08_pauta.py", "eje": "Prensa",
     "lee": ["f_dgsiaf"], "produce": ["pauta_mensual"],
     "nota": "Intensidad = devengado en publicidad / devengado total (share, invariante a la inflación). El HHI por medio era inviable: dataset congelado en 2022."},
    {"id": "sc_13", "label": "scraper_13_prensa_causas.py", "archivo": "04_Prensa_Institucional/scraper_13_prensa_causas.py", "eje": "Prensa",
     "lee": ["f_fopea"], "produce": ["prensa_causas_mensual"],
     "nota": "Event-count de la categoría FOPEA «acciones judiciales civiles o penales», ventana móvil 12m (son ~20 casos al año)."},
    {"id": "sc_20", "label": "scraper_20_medios_oficiales.py", "archivo": "04_Prensa_Institucional/scraper_20_medios_oficiales.py", "eje": "Prensa",
     "lee": ["f_dgsiaf"], "produce": ["medios_oficiales_mensual"],
     "nota": "Tamaño del aparato de medios estatales (RTA, Radio Nacional, Télam, Contenidos Públicos) sobre el gasto total."},
    {"id": "sc_22", "label": "scraper_22_acceso_prensa.py", "archivo": "04_Prensa_Institucional/scraper_22_acceso_prensa.py", "eje": "Prensa",
     "lee": ["f_fopea", "t_acreditaciones"], "produce": ["acceso_prensa_mensual"],
     "nota": "Combina el ESTADO del régimen de acceso (tabla datada) con el event-count de restricciones. El estado va en modo arrastre."},
    {"id": "sc_18", "label": "scraper_18_bcra_balance.py", "archivo": "05_Banco_Central/scraper_18_bcra_balance.py", "eje": "Banco Central",
     "lee": ["f_bcra_bal"], "produce": ["bcra_financiamiento_mensual", "bcra_letras_mensual"],
     "nota": "Una sola fuente alimenta las dos variables monetarias. Descarga siempre y refresca la caché (el bug de julio: quedaba congelado en abril)."},
    {"id": "sc_21", "label": "scraper_21_carta_organica.py", "archivo": "05_Banco_Central/scraper_21_carta_organica.py", "eje": "Banco Central",
     "lee": ["f_series", "bcra_financiamiento_mensual"], "produce": ["carta_organica_mensual"],
     "nota": "Tope del art. 20: 12% de la base + 10% de los recursos en efectivo 12m. Mide LEGALIDAD, no magnitud (esa la mide Financiamiento)."},
    {"id": "sc_17", "label": "scraper_17_bcra_designacion.py", "archivo": "05_Banco_Central/scraper_17_bcra_designacion.py", "eje": "Banco Central",
     "lee": ["t_bcra_desig"], "produce": ["bcra_designacion_mensual"],
     "nota": "Sin scraping: tabla mantenida a mano. Los tramos previos a 2019 son scaffold y hay que confirmarlos con los pliegos del Senado."},
    {"id": "sc_radar_bcra", "label": "radar_bcra.py", "archivo": "05_Banco_Central/radar_bcra.py", "eje": "Banco Central",
     "lee": ["f_bora"], "produce": ["d_bcra_eventos"], "rol": "radar (alerta)",
     "nota": "Solo alerta. Distingue «con acuerdo del Senado» (única designación válida) de «en comisión». Evita Director/Vicepresidente y el boilerplate «Presidente de la Nación»."},
    {"id": "sc_radar_nom", "label": "radar_nombramientos.py", "archivo": "07_Radar_Nombramientos/radar_nombramientos.py", "eje": "Judicial",
     "lee": ["f_bora"], "produce": ["d_altas", "d_bajas"], "rol": "radar (alerta)",
     "nota": "Corre en GitHub Actions L–V 9:30 ART. Decide leyendo el CUERPO del decreto: el título del enlace no dice «juez». Falla avisando, nunca «sin novedades»."},
    {"id": "sc_panhis", "label": "diagnostico_panhis.py", "archivo": "05_Banco_Central/diagnostico_panhis.py", "eje": "Banco Central",
     "lee": ["f_panhis"], "produce": [], "fuera": True,
     "nota": "Herramienta de diagnóstico, retirada del pipeline el 2026-08-19 (no produce serie)."},
    {"id": "sc_ensamblado", "label": "icia_ensamblado.py", "archivo": "00_Comun/icia_ensamblado.py", "eje": "Infra",
     "lee": ["cfg_variables"], "produce": ["d_mia_mensual"], "rol": "motor del índice",
     "nota": "Anclaje al ideal, suavizado 12m, ffill de estados, arrastre asimétrico y renormalización por eje. Toma siempre el CSV más nuevo de cada patrón."},
    {"id": "sc_nucleo_m", "label": "mia_nucleo_mensual.py", "archivo": "06_Historico/mia_nucleo_mensual.py", "eje": "Infra",
     "lee": ["cfg_variables"], "produce": ["d_nucleo_mensual"], "rol": "núcleo",
     "nota": "Reutiliza la maquinaria del ensamblador con las 13 variables de serie larga (2020+). Desde 2026-08-19 lee el YAML, no una lista propia."},
    {"id": "sc_nucleo_h", "label": "mia_nucleo_historico.py", "archivo": "06_Historico/mia_nucleo_historico.py", "eje": "Infra",
     "lee": ["cfg_variables"], "produce": ["d_nucleo_anual"], "rol": "núcleo",
     "nota": "Misma escala pero a frecuencia ANUAL desde 2003, para comparar gestiones."},
    {"id": "sc_validar", "label": "validar.py", "archivo": "00_Comun/validar.py", "eje": "Infra",
     "lee": ["cfg_variables", "cfg_contracts"], "produce": ["d_alertas"], "rol": "QA",
     "nota": "Notifica, no bloquea (exit 2). Chequea presencia, columnas, no-vacío y frescura contra las tolerancias de contracts.yaml."},
    {"id": "sc_archivar", "label": "archivar_historico.py", "archivo": "00_Comun/archivar_historico.py", "eje": "Infra",
     "lee": ["d_mia_mensual"], "produce": ["d_historico"], "rol": "histórico",
     "nota": "UPSERT con inmutabilidad: el mes cerrado queda congelado; reabrirlo es decisión humana explícita (--reabrir)."},
    {"id": "sc_graficar", "label": "graficar_mia.py", "archivo": "00_Comun/graficar_mia.py", "eje": "Infra",
     "lee": ["d_mia_mensual"], "produce": ["d_graficos"], "rol": "gráficos", "nota": "Consolidado, 5 ejes y núcleo."},
    {"id": "sc_reporte", "label": "generar_reporte_mensual.py", "archivo": "00_Comun/generar_reporte_mensual.py", "eje": "Infra",
     "lee": ["d_mia_mensual", "d_historico", "d_nucleo_mensual", "cfg_variables"], "produce": ["d_reporte"], "rol": "reporte",
     "nota": "Arma el .docx sobre la plantilla LyP. Todo automático salvo «La lectura de Libertad y Progreso», la única sección a mano."},
    {"id": "sc_exportar", "label": "exportar_serie_historica.py", "archivo": "00_Comun/exportar_serie_historica.py", "eje": "Infra",
     "lee": ["d_nucleo_mensual", "d_nucleo_anual", "d_historico"], "produce": ["d_excel"], "rol": "difusión",
     "nota": "Excel único 2020→ con núcleo mensual/anual, pleno mensual, variables y notas."},
]

# ── Datos: series del índice, puentes, tablas mantenidas, config y salidas ───
DATOS = [
    {"id": "d_infoleg_df", "label": "DataFrame InfoLEG", "clase": "intermedio", "eje": "Infra",
     "nota": "Salida en memoria de la librería compartida; la consumen los módulos 1, 2 y 4."},
    {"id": "d_altas", "label": "nombramientos_jueces.csv", "clase": "puente", "eje": "Judicial",
     "nota": "Puente del radar (altas). Append idempotente, dedup por URL. Solo confianza ALTA o confirmado='sí' entra al valor."},
    {"id": "d_bajas", "label": "bajas_jueces.csv", "clase": "puente", "eje": "Judicial",
     "nota": "Puente del radar (bajas: renuncia, cese, remoción, jubilación, límite de edad, fallecimiento)."},
    {"id": "d_bcra_eventos", "label": "bcra_presidencia_eventos.csv", "clase": "puente", "eje": "Banco Central",
     "nota": "Alerta del radar del BCRA. Un humano confirma y recién entonces se edita la tabla de designación."},
    {"id": "d_padron_tasas", "label": "padron_tasas_estimadas.csv", "clase": "puente", "eje": "Judicial",
     "nota": "Tasas recalculadas en vivo sobre cargos habilitados; marcan el mes corriente como «estimado»."},
    {"id": "d_padron_revision", "label": "padron_revision.csv", "clase": "salida", "eje": "Judicial",
     "nota": "Cola de revisión humana: eventos del BORA que no se pudieron mapear a un cargo."},
    {"id": "d_atn_obs", "label": "atn_obs_mensual.csv", "clase": "puente", "eje": "Ejecutivo",
     "nota": "Observaciones mensuales inmutables: el mes cerrado y publicado no se recalcula."},
    {"id": "d_integridad", "label": "integridad_mensual.csv", "clase": "salida", "eje": "Judicial", "fuera": True,
     "nota": "No lo consume ninguna variable de variables.yaml."},
    {"id": "t_presupuesto", "label": "Tabla: presupuesto aprobado por año", "clase": "tabla", "eje": "Ejecutivo",
     "nota": "PRESUPUESTO_APROBADO — verificado en el Boletín Oficial. 2023 ley, 2024 y 2025 prórroga, 2026 ley 27.798."},
    {"id": "t_informes", "label": "Tabla: informes JGM no listados", "clase": "tabla", "eje": "Legislativo",
     "nota": "INFORMES_EXTRA + CSV opcional: cubre el lag de la tabla del Senado."},
    {"id": "t_csjn", "label": "Tabla: cifras CSJN verificadas", "clase": "tabla", "eje": "Judicial",
     "nota": "Ingresados/resueltos, mediana, originaria y composición de la Corte; el auto-parse se valida contra esto."},
    {"id": "t_acreditaciones", "label": "Tabla: régimen de acceso de la prensa", "clase": "tabla", "eje": "Prensa",
     "nota": "ACREDITACIONES — tramos datados: cierre de la sala en abril 2026 y reapertura en mayo."},
    {"id": "t_bcra_desig", "label": "Tabla: designación Pdte. BCRA", "clase": "tabla", "eje": "Banco Central",
     "nota": "CONFIG por tramos. Bausili: en comisión por Decreto 19/2023, sin acuerdo del Senado."},
    {"id": "cfg_variables", "label": "variables.yaml", "clase": "config", "eje": "Infra",
     "nota": "FUENTE ÚNICA: 18 variables, ejes, pesos macro 30/20/20/15/15, anclas, modos y qué entra al núcleo (nucleo / nucleo_comp)."},
    {"id": "cfg_contracts", "label": "contracts.yaml", "clase": "config", "eje": "Infra",
     "nota": "Solo umbrales de frescura del QA; la estructura de columnas se deriva de variables.yaml."},
    {"id": "d_mia_mensual", "label": "mia_mensual.csv", "clase": "salida", "eje": "Infra",
     "nota": "El índice publicado desde 2024-01 (se calcula desde 2023-01 como colchón del suavizado)."},
    {"id": "d_historico", "label": "mia_historico.csv / .xlsx", "clase": "salida", "eje": "Infra",
     "nota": "Histórico maestro con meses cerrados congelados y el mes en curso provisional."},
    {"id": "d_nucleo_mensual", "label": "mia_nucleo_mensual.csv", "clase": "salida", "eje": "Infra",
     "nota": "Serie larga comparable 2020→. Sus niveles NO coinciden con el índice pleno."},
    {"id": "d_nucleo_anual", "label": "mia_nucleo_anual.csv", "clase": "salida", "eje": "Infra",
     "nota": "Núcleo anual 2003→ para comparar gestiones."},
    {"id": "d_alertas", "label": "_alertas_validacion.md", "clase": "salida", "eje": "Infra",
     "nota": "Reporte de QA que lee el equipo antes de publicar."},
    {"id": "d_graficos", "label": "Gráficos (PNG)", "clase": "salida", "eje": "Infra",
     "nota": "Consolidado, 5 ejes y núcleo; entran al reporte."},
    {"id": "d_reporte", "label": "Reporte mensual (.docx)", "clase": "salida", "eje": "Infra",
     "nota": "Diseño LyP. Único bloque manual: la lectura institucional."},
    {"id": "d_excel", "label": "Excel serie histórica 2020→", "clase": "salida", "eje": "Infra",
     "nota": "Para consulta y difusión."},
]

# Aristas que no salen de lee/produce: insumos que son ALERTA, no valor publicado.
EXTRA_LINKS = [
    {"source": "d_bcra_eventos", "target": "t_bcra_desig", "kind": "alerta",
     "nota": "El radar avisa; un humano confirma y edita la tabla. La IA/regex nunca toca el valor."},
]
